# Site
title:              "Helping Users Preserve the commUnity"    
bio:                "While it is natural and even healthy for some communities to evolve, far too often is this evolution to the detriment of the existing community. Nationwide, gentrification sweeps through cities, leaving behind “improved” neighborhoods that lack most of the community that originally resided within. <a href="https://www.bristolpost.co.uk/news/property/stages-gentrification-how-spot-bristols-3258368">Bristol Live</a> describes the root of gentrification as the ability of higher-income individuals to “become more organised, arranging historic preservation groups, as well as business and neighbourhood associations.” The problem, however, is that the lower-income groups lack the time and resources to arrange in a similar manner, handing over all power and preparation to the wealthy. This also means that lower-income individuals often do not know about these plans until after they have gained momentum, further lowering their opportunity to fight back. For people living in low-income, rent-controlled communities, gentrification means more than loss of local business or the inconvenience of walking an extra block to find a laundromat. In many cases, it can mean drastic increases in rent prices and often eviction, draining the rich communities that may have once existed, putting in their places rich communities filled with Starbucks and shopping malls. Though gentrification is a nationwide phenomenon affecting many Americans, those affected feel unified only in their feelings of isolation and disempowerment in the wake of their changing neighborhoods. Our design aims to raise awareness of this issue in a disruptive manner. We have selected for our design a large interactive display, to be projected on a gentrified building within an urban community. The design itself will support the task of connecting people to local politicians, as well as the task of geotagging art and other personal ideas to buildings and locations. We have chosen this design because it is by far the most eye-catching, and we believe it is an idea that could prove to be immensely impactful while synergizing the selected tasks. Additionally, it is not something that requires much effort on the part of the gentrified to still create a powerful statement."
description:        "Meet the people behind the idea."
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo3.png'
background:         'assets/img/city.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
# url:              

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
#plus:            #usernam
#analytics:
#verify:
#ad-client:
#ad-slot:
#bing-verify:
#email:
#twitter:            username
#facebook:           username
#github-url:         username
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
#linkedin:          username
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
